name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  IMAGE_NAME: php-base
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push v8.2
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:8.2
          build-args: |
            PHP_VERSION=8.2
            IMAGE_VARIANT=-bookworm

      - name: Build and push v8.2.5
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:8.2
          build-args: |
            PHP_VERSION=8.2.5

      - name: Build and push v8.3
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:8.3
          build-args: |
            PHP_VERSION=8.3
            IMAGE_VARIANT=-bookworm