name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: php8.2-base
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate SemVer tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ ! "${TAG}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "The tag ${TAG} is not a valid Semantic Version. Exiting."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract GitHub tag from GITHUB_REF
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $FULL_TAG | cut -d'.' -f1)
          echo "DOCKER_TAG=$FULL_TAG" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.MAJOR_VERSION }}
          build-args: |
            PHP_VERSION=${{ env.DOCKER_TAG }}